version:  '3.1'

services: 
  web:
    build: .
    command: ["flask", "run", "-h", "0.0.0.0", "-p", "8000"]
      # - python manage.py collectstatic --noinput
      # - 
    volumes: 
      - .:/app
      # - .:/usr/src/app/
      
    ports: 
      - "8000:8000"


